version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
    restart: always
    working_dir: /app
    command: ['tail', '-f', '/dev/null']

volumes:
  node_modules:
